### PR TITLE
Refactor `template_ws`

### PR DESCRIPTION
**Pull request by j3soon**
This refactor addresses several issues we encountered and discussed since the initial version of `template_ws`.

This also simplifies some commands, improves performance, and automate commands to make the development process more streamlined.

I would appreciate any feedback from @YuZhong-Chen and @Assume-Zhan when you have time to ensure I didn’t miss anything. If it looks good, you could submit a review by simply approve this PR, and optionally leave some comments. Thank you!

<hr>

After merging this PR, we still need to:
* Add some basic tests/linting to ensure all workspace styles are in sync with the template workspace
* Refactor all other workspace style

### CODE REVIEW

**Comment by YuZhong-Chen** [comment]
Hi, I think you missed installing Python pip in this section.

https://github.com/j3soon/ros2-essentials/blob/afdb58c658c208b7daaa6e512c8a209b7fe99961/template_ws/docker/Dockerfile#L40-L43

**Comment by j3soon** [comment]
Hi @YuZhong-Chen , I just pushed a fix, thanks!

**Comment by YuZhong-Chen** [comment]
I think we can support multi-platform builds in this PR, otherwise, it will be difficult to refactor the existing workspace, such as `husky_ws`. However, we might not support arm64 in every workspace, we may need to add some comments in the compose file to indicate whether this Dockerfile supports arm64.

To enable arm64 architecture support in `template_ws`, we can add the following lines.

https://github.com/j3soon/ros2-essentials/blob/443c2bb1d1476ed823b65a3ca732324522074584/husky_ws/docker/Dockerfile#L1-L10

https://github.com/j3soon/ros2-essentials/blob/443c2bb1d1476ed823b65a3ca732324522074584/husky_ws/docker/Dockerfile#L51-L56

https://github.com/j3soon/ros2-essentials/blob/443c2bb1d1476ed823b65a3ca732324522074584/husky_ws/docker/compose.yaml#L3-L9

**Comment by j3soon** [comment]
@YuZhong-Chen Nice suggestion! just added this.

**Comment by YuZhong-Chen** [comment]
I haven't used Docker build cache before, so I'm currently learning about it step-by-step from the [official documentation](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md#run). I believe our current Dockerfile is still missing some commands.

Here’s an example from [BuildKit](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md#example-cache-apt-packages):

```dockerfile
# syntax=docker/dockerfile:1
FROM ubuntu
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt update && apt-get --no-install-recommends install -y gcc
```

Based on the example above, we should:

- Remove `docker-clean` and add some commands in `keep-cache`. [Ref1](https://github.com/moby/buildkit/issues/1673#issuecomment-1264502398) [Ref2](https://github.com/moby/buildkit/issues/1673#issuecomment-1264742579).
- Add `sharing=private` to prevent errors when building multiple Docker images in parallel. [Ref](https://github.com/moby/buildkit/issues/1673#issuecomment-1987107404)

I'm currently not sure if we need to mount `/var/lib/apt`, because we have encountered issues before where this cache prevented us from updating apt lib lists. I prefer sticking with the existing approach: directly deleting it and regenerating it each time it's used.

If you want to learn more, I think [this website](https://vsupalov.com/buildkit-cache-mount-dockerfile/) explains it very clearly.

**Comment by YuZhong-Chen** [comment]
I'm sorry, I didn't clarify the previous example well. You should mount the cache [here](https://github.com/j3soon/ros2-essentials/blob/f8e86d96a6b91c303f736a7039839b21bae3df1e/template_ws/docker/Dockerfile#L59-L65) in commit [f8e86d9](https://github.com/j3soon/ros2-essentials/pull/44/commits/f8e86d96a6b91c303f736a7039839b21bae3df1e)

By the way, we could add some examples in the [TODO section](https://github.com/j3soon/ros2-essentials/blob/f8e86d96a6b91c303f736a7039839b21bae3df1e/template_ws/docker/Dockerfile#L73) to remind users to use the cache.

```dockerfile
# TODO: Add more commands here
# For example, to install additional packages, uncomment the following lines and add the package names
# RUN --mount=type=cache,target=/var/cache/apt \
#     apt-get update && apt-get install -y \
#     $OTHER_PACKAGES \
#     && rm -rf /var/lib/apt/lists/*
```

However, mounting the cache might involve changes, we can wait until the previous comment is resolved.

**Comment by j3soon** [comment]
@YuZhong-Chen Thanks for the info! I'm also new to this feature and learned a lot by going through the detailed references you provided. I agree with your suggestions on this issue, and just pushed a fix accordingly.

**Review by YuZhong-Chen — APPROVED** [review]
I have added some commits to fix the issues I observed. If these commits are fine, I believe the current changes can be merged into the master branch.

> By the way, should we rename the `master` branch to `main`? Although this change won’t affect anything, I prefer the `main` naming convention, and the official default branch name has been updated. You can refer to this [link](https://github.com/github/renaming) for more information.

**Comment by j3soon** [comment]
Thanks for reviewing this PR. I'll go ahead and merge it.

I agree with you and just renamed the default branch from `master` to `main`. Thanks for the reminder!

**Pull request merged**
